# Generated by Django 3.1.1 on 2020-09-19 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_data', '0004_watersummary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitysummary',
            options={'verbose_name_plural': 'Activity Summary'},
        ),
        migrations.AlterModelOptions(
            name='foodsummary',
            options={'verbose_name_plural': 'Food Summary'},
        ),
        migrations.AlterModelOptions(
            name='sleepsummary',
            options={'verbose_name_plural': 'Sleep Summary'},
        ),
        migrations.AlterModelOptions(
            name='watersummary',
            options={'verbose_name_plural': 'Water Summary'},
        ),
    ]
