# Generated by Django 3.1.1 on 2020-10-02 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_auth', '0003_auto_20200917_1956'),
        ('fitbit_data', '0005_auto_20200919_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyWeightLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('data', models.JSONField(default=dict)),
                ('fb_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to='fitbit_auth.fitbituser')),
            ],
            options={
                'verbose_name': 'Body Weight Log',
                'verbose_name_plural': 'Body Weight Logs',
            },
        ),
        migrations.CreateModel(
            name='BodyFatLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('data', models.JSONField(default=dict)),
                ('fb_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fat_logs', to='fitbit_auth.fitbituser')),
            ],
            options={
                'verbose_name': 'Body Fat Log',
                'verbose_name_plural': 'Body Fat Logs',
            },
        ),
    ]
