# Generated by Django 3.1.8 on 2021-04-07 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_data', '0007_heartratesummary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitysummary',
            options={'ordering': ['date'], 'verbose_name_plural': 'Activity Summary'},
        ),
        migrations.AlterModelOptions(
            name='bodyfatlog',
            options={'ordering': ['date'], 'verbose_name': 'Body Fat Log', 'verbose_name_plural': 'Body Fat Logs'},
        ),
        migrations.AlterModelOptions(
            name='bodyweightlog',
            options={'ordering': ['date'], 'verbose_name': 'Body Weight Log', 'verbose_name_plural': 'Body Weight Logs'},
        ),
        migrations.AlterModelOptions(
            name='foodsummary',
            options={'ordering': ['date'], 'verbose_name_plural': 'Food Summary'},
        ),
        migrations.AlterModelOptions(
            name='heartratesummary',
            options={'ordering': ['date'], 'verbose_name': 'Heart Rate Timeseries', 'verbose_name_plural': 'Heart Rate Timeseries'},
        ),
        migrations.AlterModelOptions(
            name='sleepsummary',
            options={'ordering': ['date'], 'verbose_name_plural': 'Sleep Summary'},
        ),
        migrations.AlterModelOptions(
            name='watersummary',
            options={'ordering': ['date'], 'verbose_name_plural': 'Water Summary'},
        ),
    ]
