version: '3'

services:
  db:
    image: postgres:11-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=fitbit-subscriber-db
      - POSTGRES_USER=fitbit-subscriber
      - POSTGRES_PASSWORD=pheeKoo2rie4eem4
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    restart: unless-stopped
    environment:
      - DJANGO_DEBUG=False
      - DB_PORT=5432
      - DB_ADDRESS=db
      - DB_NAME=fitbit-subscriber-db
      - DB_USER=fitbit-subscriber
      - DB_PASSWORD=pheeKoo2rie4eem4

volumes:
  db_data: {}
