version: '3'

services:
  db:
    image: postgres:11-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=fitbit-subscriber-db
      - POSTGRES_USER=fitbit-subscriber
      - POSTGRES_PASSWORD=fitbit-subscriber
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    build: .
    command: ./bin/entrypoint-local.sh
    environment:
      - DJANGO_DEBUG=True
      - DB_PORT=5432
      - DB_ADDRESS=db
      - DB_NAME=fitbit-subscriber-db
      - DB_USER=fitbit-subscriber
      - DB_PASSWORD=fitbit-subscriber
    volumes:
      - .:/opt/app:Z
    ports:
      - 8000:8000

volumes:
  db_data: {}
