# Generated by Django 3.1.1 on 2020-09-05 04:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitbituser',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
