# Generated by Django 3.1.1 on 2020-09-17 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitbit_auth', '0002_fitbituser_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbituser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fb_auth', to=settings.AUTH_USER_MODEL),
        ),
    ]
