# Generated by Django 3.1.8 on 2021-04-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitbit_auth', '0003_auto_20200917_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitbituser',
            name='profile_data',
            field=models.JSONField(default=dict),
        ),
    ]
