apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
  labels:
    app: celery-beat
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
        - name: celery-beat
          image: fitbit-subscriber:test
          command: ["bin/entrypoint-beat.sh"]
          env:
            - name: DB_NAME
              value: fitbit-subscriber-db

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password

            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP

            - name: DJANGO_DEBUG
              value: "False"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  labels:
    app: celery-worker
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: fitbit-subscriber:test
          command: ["bin/entrypoint-worker.sh"]
          env:
            - name: DB_NAME
              value: fitbit-subscriber-db

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password

            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP

            - name: DJANGO_DEBUG
              value: "False"
