apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: celery-worker
          image: nkprince007/fitbit-subscriber:0.0.1
          command: ["bin/entrypoint-worker.sh"]
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: DB_NAME
              value: fitbit-subscriber-db

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password

            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP

            - name: DJANGO_DEBUG
              value: "False"
        - name: celery-beat
          image: nkprince007/fitbit-subscriber:0.0.1
          command: ["bin/entrypoint-beat.sh"]
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: DB_NAME
              value: fitbit-subscriber-db

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password

            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP

            - name: DJANGO_DEBUG
              value: "False"
        - name: web
          image: nkprince007/fitbit-subscriber:0.0.1
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
          env:
            - name: DB_NAME
              value: fitbit-subscriber-db

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password

            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP

            - name: DJANGO_DEBUG
              value: "False"
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
